name = "impact-circle-web"
main = ".open-next/worker.js"
compatibility_date = "2024-11-18"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = ".open-next/assets"

[build]
command = "pnpm opennextjs-cloudflare build"

[placement]
mode = "smart"

[vars]
OPENNEXT_BUCKET_NAME = "ASSETS"
