steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "$_IMAGE_TAG"
      - "--build-arg"
      - "NEXT_PUBLIC_API_URL=$_NEXT_PUBLIC_API_URL"
      - "-f"
      - "apps/web/Dockerfile"
      - "."
images:
  - "$_IMAGE_TAG"
