[build]
  command = "pnpm build"
  publish = "apps/web/.next"

[build.environment]
  NODE_VERSION = "22"
  PNPM_FLAGS = "--shamefully-hoist"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/*"
  to = "https://impact-circle-api.gaurav2361.workers.dev/api/:splat"
  status = 200
  force = true
