[build]
  command = "pnpm build"
  publish = "apps/web/.next"

[build.environment]
  NODE_VERSION = "22"
  PNPM_FLAGS = "--shamefully-hoist"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = "apps/backend/src"
  node_bundler = "esbuild"
  included_files = ["apps/backend/src/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/netlify"
  status = 200
